### ISSUE TITLE
Optimize /community page load

### ISSUE THREAD

**Issue by benbalter** [github/government.github.com#342]
As the number of government organizations on GitHub has grown, so too has the load time of the /community page. 

I'm less concerned about the load time as I am about the experience of actually using it. For example, even if you know what you're looking for, it's hard to read, as your scroll, as the images load and the dom reflows. This is especially true if you enter via an anchor link (which then isn't where you want it).

I tried setting the height explicitly on images, but it didn't seem to help. Perhaps we could do one of those fancy javascript fade in loads? @jlord know this was your :baby: originally, any thoughts / strong opinions?

See also https://github.com/github/government.github.com/issues/304

**Comment by jlord** [comment]
No strong opinions. I totally agree the experience is not great right now as all these things load. 

What about losing the avatar all together? They are nice and colorful, but there are 100's now and maybe it's not worth it to have them? We'd still have some as a nice color wall on the front page. 

Though I do think that because the org names aren't very descriptive, just having then alone would look like a pretty useless blob of words (even with the country names). It would probably then be worth making a script pull all of the full usernames from the orgs that have them.

**Comment by benbalter** [comment]
This has been fixed by https://github.com/benbalter/jekyll-avatar which explicitly sets the image height.

**Comment by XhmikosR** [comment]
@benbalter: this doesn't really fix the page performance. It still loads so many elements.

My suggestion would be to lazy load the images in home and community pages.
